CREATE DATABASE SQL_DOAN_LTUD

CREATE TABLE XE
(
	MAXE NVARCHAR(10) PRIMARY KEY,
	HANGXE NVARCHAR(55),
	SOXE NVARCHAR(15),
	LOAIXE NVARCHAR(20),
	HANHTRINH NVARCHAR(30),
	GIA INT,
	GIOXUATPHAT DATETIME,
	SOGHE INT,
	SOHANHKHACH INT,
	BACTAI NVARCHAR(10),
	LOXE NVARCHAR(10),
)

DROP TABLE XE